//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseClass
{
    using System;
    using System.Collections.Generic;
    public enum STATUS
    {
        DISPONIBLE,
        OCUPADO,
        FUERA_SERVICIO
    }
    public partial class Seat
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public int Rownumber { get; set; }
        public int Columnnumber { get; set; }
        public string Seatname { get; set; }
        public string Status { get; set; }
        public Nullable<int> ProjectionId { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
