//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int ProjectionId { get; set; }
        public System.DateTime Dateofsale { get; set; }
        public int Ticketnumber { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Projection Projection { get; set; }
    }
}
